version: '3.8'

services:
  nacos:
    image: harbor.gainetics.io/observable/nacos-server:2.2.3
    container_name: nacos-standalone
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=derby
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
    ports:
      - "8848:8848"  # Nacos 控制台端口
      - "9848:9848"  # Nacos 集群通信端口
      - "9849:9849"  # Nacos 集群通信端口
    volumes:
      - ./logs:/home/nacos/logs
      - ./data:/home/nacos/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.0.70.46:8848/nacos/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - nacos

networks:
  nacos:
    name: nacos
    driver: bridge 