filebeat.inputs:
# 1. 容器日志采集
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

# 2. 文件日志采集
- type: log
  enabled: true
  paths:
    - /var/logs/*.log
  fields:
    app: application
  fields_under_root: true
  multiline:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after

# 3. 系统日志采集
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
  fields:
    type: system
  fields_under_root: true

# 4. 系统指标采集
- type: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - filesystem
    - fsstat
  period: 10s
  processors:
    - add_host_metadata: ~

# 5. 进程监控
- type: process
  enabled: true
  processes:
    - ".*"
  period: 10s

# 6. 网络数据包采集
- type: tcp
  enabled: true
  ports: [80, 443, 8080]
  fields:
    type: network
  fields_under_root: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_event:
      when:
        or:
          - equals:
              type: "debug"
          - equals:
              type: "trace"

# Kafka 输出配置
output.kafka:
  enabled: true
  hosts: ["${KAFKA_HOSTS}"]
  topic: "${KAFKA_TOPIC}"
  username: "${KAFKA_USERNAME}"
  password: "${KAFKA_PASSWORD}"
  sasl.mechanism: PLAIN
  sasl.enabled: true
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  codec.json:
    pretty: false
    escape_html: false

# 日志配置
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760 # 10MB 