version: '3.8'

networks:
  monitoring-network:
    external: true
  logging-network:
    external: true
  tracing-network:
    external: true
services:
  # Prometheus - 指标收集和存储
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-admin-api
      - --web.enable-remote-write-receiver
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=10GB
      - --query.max-concurrency=50
      - --query.timeout=2m
      - --web.max-connections=512
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - prometheus-storage:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
      - tracing-network
      - logging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - TZ=Asia/Shanghai

volumes:
  prometheus-storage: 