config.reload.automatic: ${config.reload.automatic}
config.reload.interval: ${config.reload.interval}
config.test_and_exit: ${config.test_and_exit}
dead_letter_queue.enable: false
http.host: 0.0.0.0
http.port: 9600
log.level: ${LOG_LEVEL}
node.name: logstash-simple
path.config: ${path.config}
path.data: /usr/share/logstash/data
path.logs: ${path.logs}
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.workers: 2
queue.max_bytes: 1gb
queue.max_events: 0
queue.type: memory
slowlog.threshold.debug: 500ms
slowlog.threshold.info: 1s
slowlog.threshold.trace: 100ms
slowlog.threshold.warn: 2s
xpack.monitoring.enabled: ${xpack.monitoring.enabled}
