version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./certs:/usr/share/logstash/certs:ro
    environment:
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=your_password
      - KAFKA_HOSTS=kafka:9092
      - KAFKA_TOPIC=filebeat-logs
      - KAFKA_USERNAME=your_username
      - KAFKA_PASSWORD=your_password
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - logging-network
      - kafka
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:9600 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  logging-network:
    external: true
  kafka:
    external: true