version: '3.8'

networks:
  tracing-network:
    external: true

services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # metrics
      - "8889:8889"   # prometheus metrics
      - "13133:13133" # health check
      - "4316:4317"   # OTLP gRPC
      - "4315:4318"   # OTLP HTTP
      - "1777:1777"   # pprof
    networks:
      - tracing-network
    environment:
      - GOMEMLIMIT=512MiB
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 