version: '3.8'

services:
  elasticsearch:
    image: harbor.gainetics.io/observable/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging-network
      - monitoring-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  monitoring-network:
    external: true
  logging-network:
    external: true
