data_dir: /var/lib/vector

sources:
  file_logs:
    type: file
    include:
      - /var/log/*.log
    read_from: beginning
    ignore_older: 86400  # 忽略24小时前的日志

transforms:
  parse_logs:
    type: remap
    inputs: ["file_logs"]
    source: |
      if exists(.message) {
        parsed, err = parse_json(.message)
        if err == null {
          . = parsed
        }
      }
      .timestamp = now()

sinks:
  elasticsearch:
    type: elasticsearch
    inputs: ["parse_logs"]
    endpoint: http://10.0.70.46:9200
    bulk:
      action: create
      index: "vector-logs-%Y-%m-%d"
    encoding:
      only_fields: ["message", "timestamp"]
      except_fields: []
      timestamp_format: "rfc3339"
    compression: gzip 