networks:
  tracing-network:
    external: true

services:
  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    user: root
    volumes:
      - ./tempo-single-node.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    networks:
      - tracing-network
    restart: unless-stopped
    environment:
      - TEMPO_LOG_LEVEL=info

volumes:
  tempo-data: 